app.py
from flask import Flask, Blueprint
from flask import Blueprint
from views import views



app = Flask(__name__)

app.register_blueprint(views)

# we make "appp" object from flask
if __name__ == "__main__":
    app.run(debug=True, port=8000)

# this is what we neeed to make a flask application run !!



views.py

from flask import render_template, Blueprint, request

views = Blueprint("views", __name__)

task_list = []

@views.route("/")
def home():
    return render_template("index.html")

@views.route("/contact")
def contact():
    return render_template("contact.html")

@views.route("/about")
def about():
    return render_template("about.html")

@views.route("/todos", methods=["GET", "POST"])
def todos():
    if request.method == "POST":
        task = request.form.get("task-input")
        task_list.append(task)
        print(task_list)
        return render_template("todos.html", task_list=task_list)
    return render_template("todos.html")

templates/about.html
{% extends 'base.html' %}  

{% block content %} 
<h1> welcome to the about page</h1>
{% endblock %} 

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title></title>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{url_for('views.home')}}">Nathan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('views.home')}}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('views.contact')}}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('views.about')}}">About</a>
                </li>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('views.todos')}}">To Do Tasks</a>
                </li>
        </div>
    </nav>
</head>
<div>
    <button onclick="darkMode()">Dark Mode</button>
</div>

<body id="base-body">
    {% block content %}
    {% endblock %}

    <footer onload="displayDate()"></footer>

    <footer id="date">
        <script>
            document.getElementById("date").innerHTML = Date();
        </script>
    </footer>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}  

{% block content %} 
<h1> welcome to the contact page</h1>
{% endblock %} 

templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1> Welcome to Nathan's Website</h1>
{% endblock %} 



templates/todos.html
{% extends 'base.html' %}

{% block content %}
<h1> To Do Manager</h1>
<br>
<div>
    <div id="task-box">
        <h2>New Tasks:</h2>

        <ul>
            {% for task in task_list %}
            {% if "now" in task %}
            <strong>Important</strong>
            {% endif %}
            <li>{{ task }}</li>
            {% endfor %}

        </ul>
    </div>
        <button onclick="taskHider()">Show or Hide Tasks</button>
    

            <form action="/todos" method="POST"><input type="text" name="task-input" id="task-input"><input
                    type="submit" value="Add Task"></form>

    </div>
    {% endblock %}